# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование')),
            ],
            options={
                'verbose_name_plural': 'Бренды',
                'verbose_name': 'Бренд',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', jsonfield.fields.JSONField(verbose_name='Значение')),
            ],
            options={
                'verbose_name_plural': 'Цены за товар',
                'verbose_name': 'Цена за товар',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название товара')),
                ('type', models.CharField(choices=[('lenses', 'Линзы'), ('solutions', 'Растворы'), ('drops', 'Капли'), ('accessories', 'Аксессуары')], max_length=64, verbose_name='Тип')),
                ('brand', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.Brand')),
                ('current_price', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='main.Price', verbose_name='Текущая цена')),
            ],
            options={
                'verbose_name_plural': 'Товары',
                'verbose_name': 'Товар',
            },
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_prices', to='main.Product'),
        ),
    ]
