# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160825_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='remote_id',
            field=models.CharField(default='0', max_length=7, verbose_name='ID на сайте'),
        ),
        migrations.AlterField(
            model_name='product',
            name='remote_id',
            field=models.CharField(default='0', max_length=7, verbose_name='ID на сайте'),
        ),
    ]
