# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-06 14:41
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F


def set_parsing_finish_time(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    ParseResultLog = apps.get_model("main", "ParseResultLog")
    ParseResultLog.objects.all().update(finish_time=F('date_updated'))


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170206_1740'),
    ]

    operations = [
        migrations.RunPython(set_parsing_finish_time)
    ]
