# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-27 15:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_auto_20170206_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCustomization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обночления')),
                ('template', models.CharField(choices=[('simple', 'Стандартный шаблон'), ('materialize', 'Материал дизайн')], default='simple', max_length=28, verbose_name='Шаблон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Кастомизация для пользователя',
                'verbose_name_plural': 'Кастомизация для пользователя',
            },
        ),
    ]
