# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-27 15:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_profilecustomization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecustomization',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customize', to=settings.AUTH_USER_MODEL),
        ),
    ]
